[2025-03-30 22:34:43,138] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: natality_web_data_to_gcs.download_race_lookup manual__2025-03-30T22:34:39.104526+00:00 [queued]>
[2025-03-30 22:34:43,154] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: natality_web_data_to_gcs.download_race_lookup manual__2025-03-30T22:34:39.104526+00:00 [queued]>
[2025-03-30 22:34:43,155] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2025-03-30 22:34:43,155] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2025-03-30 22:34:43,155] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2025-03-30 22:34:43,172] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_race_lookup> on 2025-03-30 22:34:39.104526+00:00
[2025-03-30 22:34:43,189] {standard_task_runner.py:52} INFO - Started process 1738 to run task
[2025-03-30 22:34:43,195] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'natality_web_data_to_gcs', 'download_race_lookup', 'manual__2025-03-30T22:34:39.104526+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/bigquery_to_gcs.py', '--cfg-path', '/tmp/tmp4qfw2bqc', '--error-file', '/tmp/tmp_8dfks8t']
[2025-03-30 22:34:43,201] {standard_task_runner.py:77} INFO - Job 125: Subtask download_race_lookup
[2025-03-30 22:34:43,313] {logging_mixin.py:109} INFO - Running <TaskInstance: natality_web_data_to_gcs.download_race_lookup manual__2025-03-30T22:34:39.104526+00:00 [running]> on host 6e74f7e5ce4c
[2025-03-30 22:34:43,415] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=natality_web_data_to_gcs
AIRFLOW_CTX_TASK_ID=download_race_lookup
AIRFLOW_CTX_EXECUTION_DATE=2025-03-30T22:34:39.104526+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-03-30T22:34:39.104526+00:00
[2025-03-30 22:34:43,420] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-03-30 22:34:43,421] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'wget --no-check-certificate "https://drive.google.com/file/d/17o8e1eh7XkHk61P5JuBAi2JhFvnUt4tJ/view?usp=drive_link" -O /tmp/race_lookup.csv']
[2025-03-30 22:34:43,444] {subprocess.py:85} INFO - Output:
[2025-03-30 22:34:43,451] {subprocess.py:89} INFO - --2025-03-30 22:34:43--  https://drive.google.com/file/d/17o8e1eh7XkHk61P5JuBAi2JhFvnUt4tJ/view?usp=drive_link
[2025-03-30 22:34:43,462] {subprocess.py:89} INFO - Resolving drive.google.com (drive.google.com)... 173.194.193.101, 173.194.193.138, 173.194.193.113, ...
[2025-03-30 22:34:43,464] {subprocess.py:89} INFO - Connecting to drive.google.com (drive.google.com)|173.194.193.101|:443... connected.
[2025-03-30 22:34:43,740] {subprocess.py:89} INFO - HTTP request sent, awaiting response... 200 OK
[2025-03-30 22:34:43,740] {subprocess.py:89} INFO - Length: unspecified [text/html]
[2025-03-30 22:34:43,740] {subprocess.py:89} INFO - Saving to: ‘/tmp/race_lookup.csv’
[2025-03-30 22:34:43,740] {subprocess.py:89} INFO - 
[2025-03-30 22:34:43,743] {subprocess.py:89} INFO -      0K .......... .......... .......... ...                   13.6M=0.002s
[2025-03-30 22:34:43,743] {subprocess.py:89} INFO - 
[2025-03-30 22:34:43,743] {subprocess.py:89} INFO - 2025-03-30 22:34:43 (13.6 MB/s) - ‘/tmp/race_lookup.csv’ saved [34288]
[2025-03-30 22:34:43,744] {subprocess.py:89} INFO - 
[2025-03-30 22:34:43,745] {subprocess.py:93} INFO - Command exited with return code 0
[2025-03-30 22:34:43,787] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=natality_web_data_to_gcs, task_id=download_race_lookup, execution_date=20250330T223439, start_date=20250330T223443, end_date=20250330T223443
[2025-03-30 22:34:43,818] {local_task_job.py:154} INFO - Task exited with return code 0
[2025-03-30 22:34:43,897] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
