[2025-03-30 22:22:11,632] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: natality_web_data_to_gcs.download_race_lookup manual__2025-03-30T22:22:07.463298+00:00 [queued]>
[2025-03-30 22:22:11,651] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: natality_web_data_to_gcs.download_race_lookup manual__2025-03-30T22:22:07.463298+00:00 [queued]>
[2025-03-30 22:22:11,651] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2025-03-30 22:22:11,652] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2025-03-30 22:22:11,652] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2025-03-30 22:22:11,674] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_race_lookup> on 2025-03-30 22:22:07.463298+00:00
[2025-03-30 22:22:11,687] {standard_task_runner.py:52} INFO - Started process 394 to run task
[2025-03-30 22:22:11,691] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'natality_web_data_to_gcs', 'download_race_lookup', 'manual__2025-03-30T22:22:07.463298+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/bigquery_to_gcs.py', '--cfg-path', '/tmp/tmpvz1u2g_t', '--error-file', '/tmp/tmp2k7x1h1b']
[2025-03-30 22:22:11,696] {standard_task_runner.py:77} INFO - Job 91: Subtask download_race_lookup
[2025-03-30 22:22:11,789] {logging_mixin.py:109} INFO - Running <TaskInstance: natality_web_data_to_gcs.download_race_lookup manual__2025-03-30T22:22:07.463298+00:00 [running]> on host 6e74f7e5ce4c
[2025-03-30 22:22:11,877] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=natality_web_data_to_gcs
AIRFLOW_CTX_TASK_ID=download_race_lookup
AIRFLOW_CTX_EXECUTION_DATE=2025-03-30T22:22:07.463298+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-03-30T22:22:07.463298+00:00
[2025-03-30 22:22:11,881] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-03-30 22:22:11,882] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'wget --no-check-certificate "https://drive.google.com/file/d/17o8e1eh7XkHk61P5JuBAi2JhFvnUt4tJ/view?usp=drive_link" -O /tmp/race_lookup.csv']
[2025-03-30 22:22:11,909] {subprocess.py:85} INFO - Output:
[2025-03-30 22:22:11,917] {subprocess.py:89} INFO - --2025-03-30 22:22:11--  https://drive.google.com/file/d/17o8e1eh7XkHk61P5JuBAi2JhFvnUt4tJ/view?usp=drive_link
[2025-03-30 22:22:11,927] {subprocess.py:89} INFO - Resolving drive.google.com (drive.google.com)... 173.194.193.139, 173.194.193.102, 173.194.193.100, ...
[2025-03-30 22:22:11,929] {subprocess.py:89} INFO - Connecting to drive.google.com (drive.google.com)|173.194.193.139|:443... connected.
[2025-03-30 22:22:12,407] {subprocess.py:89} INFO - HTTP request sent, awaiting response... 200 OK
[2025-03-30 22:22:12,407] {subprocess.py:89} INFO - Length: unspecified [text/html]
[2025-03-30 22:22:12,408] {subprocess.py:89} INFO - Saving to: ‘/tmp/race_lookup.csv’
[2025-03-30 22:22:12,408] {subprocess.py:89} INFO - 
[2025-03-30 22:22:12,412] {subprocess.py:89} INFO -      0K .......... .......... .......... .......... .......... 11.1M
[2025-03-30 22:22:12,416] {subprocess.py:89} INFO -     50K .......... .......... .......... ..........            10.7M=0.008s
[2025-03-30 22:22:12,416] {subprocess.py:89} INFO - 
[2025-03-30 22:22:12,417] {subprocess.py:89} INFO - 2025-03-30 22:22:12 (10.9 MB/s) - ‘/tmp/race_lookup.csv’ saved [92931]
[2025-03-30 22:22:12,417] {subprocess.py:89} INFO - 
[2025-03-30 22:22:12,418] {subprocess.py:93} INFO - Command exited with return code 0
[2025-03-30 22:22:12,457] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=natality_web_data_to_gcs, task_id=download_race_lookup, execution_date=20250330T222207, start_date=20250330T222211, end_date=20250330T222212
[2025-03-30 22:22:12,514] {local_task_job.py:154} INFO - Task exited with return code 0
[2025-03-30 22:22:12,588] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
