[2025-03-31 01:55:26,584] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: natality_web_data_to_gcs.submit_pyspark_job manual__2025-03-31T01:50:32.724355+00:00 [queued]>
[2025-03-31 01:55:26,606] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: natality_web_data_to_gcs.submit_pyspark_job manual__2025-03-31T01:50:32.724355+00:00 [queued]>
[2025-03-31 01:55:26,606] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2025-03-31 01:55:26,607] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2025-03-31 01:55:26,607] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2025-03-31 01:55:26,629] {taskinstance.py:1259} INFO - Executing <Task(DataprocSubmitJobOperator): submit_pyspark_job> on 2025-03-31 01:50:32.724355+00:00
[2025-03-31 01:55:26,639] {standard_task_runner.py:52} INFO - Started process 9181 to run task
[2025-03-31 01:55:26,645] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'natality_web_data_to_gcs', 'submit_pyspark_job', 'manual__2025-03-31T01:50:32.724355+00:00', '--job-id', '526', '--raw', '--subdir', 'DAGS_FOLDER/bigquery_to_gcs.py', '--cfg-path', '/tmp/tmp23zkrdlj', '--error-file', '/tmp/tmpk1q50qv1']
[2025-03-31 01:55:26,651] {standard_task_runner.py:77} INFO - Job 526: Subtask submit_pyspark_job
[2025-03-31 01:55:26,753] {logging_mixin.py:109} INFO - Running <TaskInstance: natality_web_data_to_gcs.submit_pyspark_job manual__2025-03-31T01:50:32.724355+00:00 [running]> on host 3341a2d56eeb
[2025-03-31 01:55:26,843] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=natality_web_data_to_gcs
AIRFLOW_CTX_TASK_ID=submit_pyspark_job
AIRFLOW_CTX_EXECUTION_DATE=2025-03-31T01:50:32.724355+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-03-31T01:50:32.724355+00:00
[2025-03-31 01:55:26,844] {dataproc.py:1997} INFO - Submitting job
[2025-03-31 01:55:26,845] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-03-31 01:55:26,989] {dataproc.py:2009} INFO - Job bf4887d0-3dba-4028-960a-da8073d000f3 submitted successfully.
[2025-03-31 01:55:27,011] {dataproc.py:2022} INFO - Waiting for job bf4887d0-3dba-4028-960a-da8073d000f3 to complete
[2025-03-31 01:55:57,356] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/operators/dataproc.py", line 2024, in execute
    job_id=job_id, region=self.region, project_id=self.project_id, timeout=self.wait_timeout
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/dataproc.py", line 871, in wait_for_job
    raise AirflowException(f'Job failed:\n{job}')
airflow.exceptions.AirflowException: Job failed:
reference {
  project_id: "us-natality-455214"
  job_id: "bf4887d0-3dba-4028-960a-da8073d000f3"
}
placement {
  cluster_name: "us-natality-cluster"
  cluster_uuid: "3d3681da-1aea-4f3d-95dc-b3a22f8d9b7f"
}
pyspark_job {
  main_python_file_uri: "scripts/pyspark_to_bq.py"
}
status {
  state: ERROR
  details: "Path \'scripts/pyspark_to_bq.py\' must have scheme."
  state_start_time {
    seconds: 1743386154
    nanos: 80726000
  }
}
status_history {
  state: PENDING
  state_start_time {
    seconds: 1743386126
    nanos: 974398000
  }
}
status_history {
  state: SETUP_DONE
  state_start_time {
    seconds: 1743386127
    nanos: 6537000
  }
}
status_history {
  state: RUNNING
  state_start_time {
    seconds: 1743386127
    nanos: 502956000
  }
}
driver_control_files_uri: "gs://dataproc-staging-us-central1-1024460416669-x0nayiua/google-cloud-dataproc-metainfo/3d3681da-1aea-4f3d-95dc-b3a22f8d9b7f/jobs/bf4887d0-3dba-4028-960a-da8073d000f3/"
driver_output_resource_uri: "gs://dataproc-staging-us-central1-1024460416669-x0nayiua/google-cloud-dataproc-metainfo/3d3681da-1aea-4f3d-95dc-b3a22f8d9b7f/jobs/bf4887d0-3dba-4028-960a-da8073d000f3/driveroutput"
job_uuid: "bf4887d0-3dba-4028-960a-da8073d000f3"
done: true

[2025-03-31 01:55:57,369] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=natality_web_data_to_gcs, task_id=submit_pyspark_job, execution_date=20250331T015032, start_date=20250331T015526, end_date=20250331T015557
[2025-03-31 01:55:57,397] {standard_task_runner.py:92} ERROR - Failed to execute job 526 for task submit_pyspark_job
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/operators/dataproc.py", line 2024, in execute
    job_id=job_id, region=self.region, project_id=self.project_id, timeout=self.wait_timeout
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/dataproc.py", line 871, in wait_for_job
    raise AirflowException(f'Job failed:\n{job}')
airflow.exceptions.AirflowException: Job failed:
reference {
  project_id: "us-natality-455214"
  job_id: "bf4887d0-3dba-4028-960a-da8073d000f3"
}
placement {
  cluster_name: "us-natality-cluster"
  cluster_uuid: "3d3681da-1aea-4f3d-95dc-b3a22f8d9b7f"
}
pyspark_job {
  main_python_file_uri: "scripts/pyspark_to_bq.py"
}
status {
  state: ERROR
  details: "Path \'scripts/pyspark_to_bq.py\' must have scheme."
  state_start_time {
    seconds: 1743386154
    nanos: 80726000
  }
}
status_history {
  state: PENDING
  state_start_time {
    seconds: 1743386126
    nanos: 974398000
  }
}
status_history {
  state: SETUP_DONE
  state_start_time {
    seconds: 1743386127
    nanos: 6537000
  }
}
status_history {
  state: RUNNING
  state_start_time {
    seconds: 1743386127
    nanos: 502956000
  }
}
driver_control_files_uri: "gs://dataproc-staging-us-central1-1024460416669-x0nayiua/google-cloud-dataproc-metainfo/3d3681da-1aea-4f3d-95dc-b3a22f8d9b7f/jobs/bf4887d0-3dba-4028-960a-da8073d000f3/"
driver_output_resource_uri: "gs://dataproc-staging-us-central1-1024460416669-x0nayiua/google-cloud-dataproc-metainfo/3d3681da-1aea-4f3d-95dc-b3a22f8d9b7f/jobs/bf4887d0-3dba-4028-960a-da8073d000f3/driveroutput"
job_uuid: "bf4887d0-3dba-4028-960a-da8073d000f3"
done: true

[2025-03-31 01:55:57,428] {local_task_job.py:154} INFO - Task exited with return code 1
[2025-03-31 01:55:57,497] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
