[2025-03-30 22:27:31,789] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: natality_web_data_to_gcs.download_race_lookup manual__2025-03-30T22:27:26.655027+00:00 [queued]>
[2025-03-30 22:27:31,808] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: natality_web_data_to_gcs.download_race_lookup manual__2025-03-30T22:27:26.655027+00:00 [queued]>
[2025-03-30 22:27:31,808] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2025-03-30 22:27:31,808] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2025-03-30 22:27:31,808] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2025-03-30 22:27:31,832] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_race_lookup> on 2025-03-30 22:27:26.655027+00:00
[2025-03-30 22:27:31,848] {standard_task_runner.py:52} INFO - Started process 901 to run task
[2025-03-30 22:27:31,854] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'natality_web_data_to_gcs', 'download_race_lookup', 'manual__2025-03-30T22:27:26.655027+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/bigquery_to_gcs.py', '--cfg-path', '/tmp/tmpge2q9u3n', '--error-file', '/tmp/tmphidco0c_']
[2025-03-30 22:27:31,859] {standard_task_runner.py:77} INFO - Job 104: Subtask download_race_lookup
[2025-03-30 22:27:31,951] {logging_mixin.py:109} INFO - Running <TaskInstance: natality_web_data_to_gcs.download_race_lookup manual__2025-03-30T22:27:26.655027+00:00 [running]> on host 6e74f7e5ce4c
[2025-03-30 22:27:32,048] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=natality_web_data_to_gcs
AIRFLOW_CTX_TASK_ID=download_race_lookup
AIRFLOW_CTX_EXECUTION_DATE=2025-03-30T22:27:26.655027+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-03-30T22:27:26.655027+00:00
[2025-03-30 22:27:32,051] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-03-30 22:27:32,052] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'wget --no-check-certificate "https://drive.google.com/file/d/17o8e1eh7XkHk61P5JuBAi2JhFvnUt4tJ/view?usp=drive_link" -O /tmp/race_lookup.csv']
[2025-03-30 22:27:32,079] {subprocess.py:85} INFO - Output:
[2025-03-30 22:27:32,087] {subprocess.py:89} INFO - --2025-03-30 22:27:32--  https://drive.google.com/file/d/17o8e1eh7XkHk61P5JuBAi2JhFvnUt4tJ/view?usp=drive_link
[2025-03-30 22:27:32,097] {subprocess.py:89} INFO - Resolving drive.google.com (drive.google.com)... 108.177.121.101, 108.177.121.139, 108.177.121.100, ...
[2025-03-30 22:27:32,099] {subprocess.py:89} INFO - Connecting to drive.google.com (drive.google.com)|108.177.121.101|:443... connected.
[2025-03-30 22:27:32,370] {subprocess.py:89} INFO - HTTP request sent, awaiting response... 200 OK
[2025-03-30 22:27:32,371] {subprocess.py:89} INFO - Length: unspecified [text/html]
[2025-03-30 22:27:32,371] {subprocess.py:89} INFO - Saving to: ‘/tmp/race_lookup.csv’
[2025-03-30 22:27:32,371] {subprocess.py:89} INFO - 
[2025-03-30 22:27:32,374] {subprocess.py:89} INFO -      0K .......... .......... .......... .......... .......... 13.3M
[2025-03-30 22:27:32,378] {subprocess.py:89} INFO -     50K .......... .......... .......... ..........            14.2M=0.006s
[2025-03-30 22:27:32,378] {subprocess.py:89} INFO - 
[2025-03-30 22:27:32,379] {subprocess.py:89} INFO - 2025-03-30 22:27:32 (13.7 MB/s) - ‘/tmp/race_lookup.csv’ saved [92793]
[2025-03-30 22:27:32,379] {subprocess.py:89} INFO - 
[2025-03-30 22:27:32,381] {subprocess.py:93} INFO - Command exited with return code 0
[2025-03-30 22:27:32,459] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=natality_web_data_to_gcs, task_id=download_race_lookup, execution_date=20250330T222726, start_date=20250330T222731, end_date=20250330T222732
[2025-03-30 22:27:32,516] {local_task_job.py:154} INFO - Task exited with return code 0
[2025-03-30 22:27:32,589] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
